import Head from 'next/head';
import Image from 'next/image';

import { UserSignup } from '/components/Auth/UserSignup';
import { UserLogin } from '/components/Auth/UserLogin';
import { Test } from '/app/test';

export default function Home() {
  return (
    <div className="home">
      <Test />
      <Head>
        <title>Fourty-io</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="home__landing-hero">
        <span>
          <h1 className="home__title">Fourty-io</h1>
        </span>
        <div className="home__login-signup-btn">
          <UserLogin />
          <UserSignup />
        </div>
      </section>
      <section className="home__about-section">
        <h2>About</h2>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
          minim veniam, quis nostrud exercitation ullamco laboris nisi ut
          aliquip ex ea commodo consequat. Duis aute irure dolor in
          reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
          pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
          culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum
          dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
          incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
          commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
          velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint
          occaecat cupidatat non proident, sunt in culpa qui officia deserunt
          mollit anim id est laborum.
        </p>
      </section>
      {/* <Image
            src="/images/landing/landing_2.webp" // Route of the image file
            height={878} // Desired size with correct aspect ratio
            width={878} // Desired size with correct aspect ratio
            layout="responsive"
            objectFit="cover"
            position="fixed"
            alt="mother and baby holding hands"
          /> */}

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
